//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequerimientosST.BL.Models
{
    using System.Data.Entity;

    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("DBContext")
        {
        }

        public static DBContext Create()
        {
            return new DBContext();
        }

        public virtual DbSet<Applicative> Applicative { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<DevelopmentEngineer> DevelopmentEngineer { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Requirement> Requirement { get; set; }
    }
}
