//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequerimientosST.BL.Models
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Requirement", Schema = "dbo")]
    public partial class Requirement
    {
        public int ID { get; set; }

        [ForeignKey("Area")]
        public Nullable<int> AreaID { get; set; }
        [ForeignKey("Applicative")]
        public Nullable<int> ApplicativeID { get; set; }
        public string ScopeRequirement { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        [ForeignKey("Priority")]
        public Nullable<int> PriorityID { get; set; }
        [ForeignKey("DevelopmentEngineer")]
        public Nullable<int> DevelopmentEngineerID { get; set; }
        public Nullable<int> DevelopmentDays { get; set; }
        public Nullable<System.DateTime> DevelopmentDate { get; set; }
    
        public virtual Applicative Applicative { get; set; }
        public virtual Area Area { get; set; }
        public virtual DevelopmentEngineer DevelopmentEngineer { get; set; }
        public virtual Priority Priority { get; set; }
    }
}
